language: node_js
before_install:
    - npm config set depth 0
    - npm install --global npm@3
node_js:
    - 6
    - 5
    - 4
install:
    - npm install
notifications:
    email: false
sudo: false
